variables:
  libiioPipelineId: 9

trigger:
  branches:
    include:
    - main
    - master
    - staging/*
    - 20*

pr:
  branches:
    include:
    - main
    - master
    - 20*

jobs:
- job: LinuxBuilds
  strategy:
    matrix:
      ubuntu_18_04_x86_64:
        imageName: 'ubuntu-18.04'
        OS_TYPE: 'ubuntu_docker'
        OS_VERSION: bionic
        artifactName: 'Linux-Ubuntu-18.04'
        PACKAGE_TO_INSTALL: 'build/*.deb'
      ubuntu_20_04_x86_64:
        imageName: 'ubuntu-20.04'
        OS_TYPE: 'ubuntu_docker'
        OS_VERSION: focal
        artifactName: 'Linux-Ubuntu-20.04'
        PACKAGE_TO_INSTALL: 'build/*.deb'
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - script: ./CI/travis/before_install_linux
    displayName: "Install Dependencies"
  - script: ./CI/travis/make_linux
    displayName: "Build"
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.BuildDirectory)/s/build/'
      contents: '$(Agent.BuildDirectory)/s/build/?(*.deb|*.rpm)'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(artifactName)'

- job: ARMBuilds
  # Host Box
  pool:
    vmImage: "ubuntu-latest"
  # Docker Images
  strategy:
    matrix:
      ubuntu-ppc64le:
        image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
        arch: ppc64le
        build_script: ci-ubuntu.sh
        artifactName: 'Ubuntu-ppc64le'
      ubuntu-x390x:
        image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
        arch: s390x
        build_script: ci-ubuntu.sh
        artifactName: 'Ubuntu-x390x'
      debian_buster_arm32v7:
        image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
        arch: arm
        build_script: ci-ubuntu.sh
        artifactName: 'Ubuntu-arm32v7'
      debian_buster_arm64v8:
        image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
        arch: aarch64
        build_script: ci-ubuntu.sh
        artifactName: 'Ubuntu-arm64v8'
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - script: |
      set -e 
      sudo apt-get install -y gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
      sudo apt-get install -y g++-arm-linux-gnueabihf
      sudo apt-get install -y g++-aarch64-linux-gnu
      sudo apt-get install -y qemu-system-ppc64
      sudo apt-get install qemu binfmt-support qemu-user-static
      sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    displayName: "Setup"
  - script: |
      set -e
      sudo docker run --platform "linux/$(arch)" --rm -t --privileged -e ARTIFACTNAME=$(artifactName) -v "$(Agent.BuildDirectory)/s":"/ci" -v "/usr/bin/qemu-$(arch)-static":"/usr/bin/qemu-$(arch)-static" "$(image)" /bin/bash -c "cd /ci/ && chmod +x ./CI/travis/$(build_script) && ./CI/travis/$(build_script)"
    displayName: "Build"
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.BuildDirectory)/s/build/'
      contents: '$(Agent.BuildDirectory)/s/build/?(*.deb|*.rpm)'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(artifactName)'

- job: macOSBuilds
  strategy:
    matrix:
      macOS_10_15:
        imageName: 'macOS-10.15'
        artifactName: 'macOS-10.15'
      macOS_11:
        imageName: 'macOS-11'
        artifactName: 'macOS-11'
  pool:
    vmImage: $(imageName)
  variables:
    PACKAGE_TO_INSTALL: 'build/*.pkg'
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - script: ./CI/travis/before_install_darwin
    displayName: "Install Dependencies"
  - script: ./CI/travis/make_darwin
    displayName: "Build"
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.BuildDirectory)/s/build/'
      contents: '$(Agent.BuildDirectory)/s/build/?(*.pkg)'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(artifactName)'

- job: WindowsBuilds
  strategy:
    matrix:
      VS2022:
          imageName: 'windows-2022'
          COMPILER: 'Visual Studio 17 2022'
          ARCH: 'x64'
          artifactName: 'Windows-VS-2022-x64'
      VS2019_Win64:
        imageName: 'windows-2019'
        COMPILER: 'Visual Studio 16 2019'
        ARCH: 'x64'
        artifactName: 'Windows-VS-2019-x64'
  pool:
    vmImage: $[ variables['imageName'] ]
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: .\CI\install_deps_win.ps1
    displayName: Dependencies
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: .\CI\build_win.ps1
    displayName: Build
  - task: CopyFiles@2
    displayName: 'Copy libraries'
    inputs:
      sourceFolder: '$(Agent.BuildDirectory)/s/build/Release'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: CopyFiles@2
    displayName: 'Copy ad9361.h header'
    inputs:
      sourceFolder: '$(Agent.BuildDirectory)/s/'
      contents: 'ad9361.h'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(artifactName)'
